# SPDX-FileCopyrightText: 2026 Hari Srinivasan <harisrini21@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-only

"""OpenCode telemetry plugin source."""

from __future__ import annotations

OPENCODE_PLUGIN_VERSION = "3"

OPENCODE_PLUGIN_SOURCE = """// Observal telemetry plugin for OpenCode
// Auto-generated by `observal doctor patch`
// Do not edit manually, regenerated on upgrade.

import { readFileSync, existsSync } from "fs";
import { join } from "path";

const OBSERVAL_PLUGIN_VERSION = "__OPENCODE_PLUGIN_VERSION__";
const HOME = process.env.HOME || process.env.USERPROFILE || "~";
const CONFIG_PATH = join(HOME, ".observal", "config.json");
const LOCKFILE_PATH = join(HOME, ".observal", "lockfile.json");
const BUILTIN_AGENTS = new Set(["build", "plan", "general", "explore", "scout", "compaction", "title", "summary"]);

function loadConfig() {
  try {
    if (!existsSync(CONFIG_PATH)) return null;
    const raw = readFileSync(CONFIG_PATH, "utf-8");
    const cfg = JSON.parse(raw);
    const token = cfg.api_key || cfg.access_token;
    if (!cfg.server_url || !token) return null;
    return { server_url: cfg.server_url, token };
  } catch {
    return null;
  }
}

function loadLockfile() {
  try {
    if (!existsSync(LOCKFILE_PATH)) return null;
    return JSON.parse(readFileSync(LOCKFILE_PATH, "utf-8"));
  } catch {
    return null;
  }
}

function resolveAgent(agentName, directory) {
  if (!agentName || BUILTIN_AGENTS.has(agentName)) return null;
  const agents = loadLockfile()?.harnesses?.opencode?.agents;
  if (!Array.isArray(agents)) return null;
  const matches = agents.filter((agent) => agent?.name === agentName || agent?.id === agentName);
  if (matches.length === 0) return null;
  const chosen =
    matches.find((agent) => agent?.scope === "project" && agent?.directory === directory) ||
    matches.find((agent) => agent?.scope !== "project") ||
    matches[0];
  if (!chosen?.id) return null;
  return { id: chosen.id, version: chosen.version || null };
}

async function log(client, level, message, extra = {}) {
  try {
    await client.app.log({ body: { service: "observal", level, message, extra } });
  } catch {
  }
}

async function pushToServer(client, payload) {
  const config = loadConfig();
  if (!config) {
    await log(client, "warn", "missing Observal config");
    return;
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);
  try {
    const response = await fetch(`${config.server_url}/api/v1/ingest/session`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${config.token}`,
      },
      body: JSON.stringify(payload),
      signal: controller.signal,
    });
    if (!response.ok) {
      await log(client, "warn", "Observal ingest rejected OpenCode session", { status: response.status, session_id: payload.session_id });
    }
  } catch (error) {
    await log(client, "error", "Observal ingest failed for OpenCode session", { session_id: payload.session_id, error: String(error) });
  } finally {
    clearTimeout(timeout);
  }
}

const sessionState = new Map();
const MAX_TRACKED_SESSIONS = 50;

function getState(sessionId) {
  if (!sessionState.has(sessionId)) {
    if (sessionState.size >= MAX_TRACKED_SESSIONS) {
      const oldest = sessionState.keys().next().value;
      sessionState.delete(oldest);
    }
    sessionState.set(sessionId, { pushedMessageIds: new Set(), lineOffset: 0, agentName: null });
  }
  return sessionState.get(sessionId);
}

function cleanupSession(sessionId) {
  sessionState.delete(sessionId);
}

function messagesToLines(messages) {
  const lines = [];
  for (const msg of messages) {
    const info = msg.info || msg;
    const parts = msg.parts || [];
    const content = [];
    for (const part of parts) {
      if (part.type === "text") {
        content.push({ type: "text", text: part.text || "" });
      } else if (part.type === "tool-invocation" || part.type === "tool_use") {
        content.push({ type: "tool_use", id: part.toolInvocationId || part.id || "", name: part.toolName || part.name || "", input: part.args || part.input || {} });
      } else if (part.type === "tool-result" || part.type === "tool_result") {
        content.push({ type: "tool_result", tool_use_id: part.toolInvocationId || part.tool_use_id || "", content: part.result || part.content || "" });
      } else if (part.type === "reasoning" || part.type === "thinking") {
        content.push({ type: "thinking", thinking: part.text || part.thinking || "" });
      }
    }
    const role = info.role || "assistant";
    let ts = new Date().toISOString();
    if (info.createdAt && typeof info.createdAt === "string") { ts = info.createdAt; }
    else if (info.time && typeof info.time === "object" && info.time.created) { ts = new Date(info.time.created).toISOString(); }
    else if (info.time && typeof info.time === "string") { ts = info.time; }
    else if (info.timestamp && typeof info.timestamp === "string") { ts = info.timestamp; }
    const line = {
      type: role === "user" ? "user" : "assistant",
      timestamp: ts,
      uuid: info.id || "",
      parentUuid: info.parentID || info.parentId || "",
      message: { role, content, model: info.modelID || info.model || "" },
    };
    if (info.tokens || info.usage) {
      const usage = info.tokens || info.usage || {};
      line.message.usage = {
        input_tokens: usage.input || usage.inputTokens || 0,
        output_tokens: usage.output || usage.outputTokens || 0,
        cache_read_input_tokens: usage.cacheRead || usage.cacheReadTokens || 0,
        cache_creation_input_tokens: usage.cacheWrite || usage.cacheWriteTokens || 0,
      };
    }
    lines.push(JSON.stringify(line));
  }
  return lines;
}

function sessionIdFrom(event) {
  return event?.properties?.sessionID || event?.properties?.info?.id || "";
}

function agentFrom(event) {
  return event?.properties?.agent || event?.properties?.info?.agent || "";
}

export const ObservalPlugin = async ({ project, client, directory }) => {
  const pendingPush = new Map();

  return {
    event: async ({ event }) => {
      const sessionId = sessionIdFrom(event);

      if (event?.type === "session.created") {
        const agentName = agentFrom(event);
        const agent = resolveAgent(agentName, directory);
        if (sessionId && agent) {
          const state = getState(sessionId);
          state.agentName = agentName;
          pendingPush.set(sessionId, true);
        }
      }

      if (event?.type === "session.updated" || event?.type === "session.next.agent.switched") {
        const agentName = agentFrom(event);
        const agent = resolveAgent(agentName, directory);
        if (sessionId && agent) {
          const state = getState(sessionId);
          state.agentName = agentName;
          pendingPush.set(sessionId, true);
        }
      }

      if (event?.type === "message.updated") {
        if (sessionId && sessionState.has(sessionId)) {
          pendingPush.set(sessionId, true);
        }
      }

      if (event?.type === "session.idle") {
        if (!sessionId) return;
        const state = sessionState.get(sessionId);
        if (!state?.agentName) return;
        const agent = resolveAgent(state.agentName, directory);
        if (!agent) return;
        if (!pendingPush.get(sessionId)) return;
        pendingPush.delete(sessionId);

        try {
          const messagesResult = await client.session.messages({ path: { id: sessionId } });
          const messages = messagesResult?.data || messagesResult || [];
          if (!Array.isArray(messages) || messages.length === 0) return;
          const newMessages = messages.filter((m) => !state.pushedMessageIds.has(m.info?.id || m.id));
          if (newMessages.length === 0) return;
          const lines = messagesToLines(newMessages);
          if (lines.length === 0) return;
          const isFinal = event?.properties?.final === true || event?.properties?.reason === "completed";
          await pushToServer(client, {
            session_id: sessionId,
            harness: "opencode",
            lines,
            agent_id: agent.id,
            agent_version: agent.version,
            start_offset: state.lineOffset,
            hook_event: "session.idle",
            final: isFinal,
            total_line_count: state.lineOffset + lines.length,
            total_offset: state.lineOffset + lines.length,
          });
          for (const m of newMessages) state.pushedMessageIds.add(m.info?.id || m.id);
          state.lineOffset += lines.length;
          if (isFinal) {
            cleanupSession(sessionId);
          }
        } catch (error) {
          await log(client, "error", "OpenCode plugin failed to export session", { session_id: sessionId, error: String(error) });
        }
      }
    },
  };
};
""".replace("__OPENCODE_PLUGIN_VERSION__", OPENCODE_PLUGIN_VERSION)
