# SPDX-FileCopyrightText: 2026 Ravi Chopra <shivamchopra1234567890@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-only
{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "observal.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observal.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  serviceName: {{ include "observal.fullname" . }}-db
  replicas: 1
  selector:
    matchLabels:
      {{- include "observal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: db
  template:
    metadata:
      labels:
        {{- include "observal.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db
    spec:
      containers:
        - name: postgresql
          image: {{ include "observal.image" (dict "global" .Values.global "image" .Values.postgresql.image) }}
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: POSTGRES_DB
              value: "observal"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "observal.secretName" . }}
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
              name: postgresql
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.postgresql.storage.storageClassName }}
        storageClassName: {{ .Values.postgresql.storage.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.storage.size | quote }}
{{- end }}
