# SPDX-FileCopyrightText: 2026 Ravi Chopra <shivamchopra1234567890@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-only
{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "observal.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observal.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "observal.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "observal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "observal.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ include "observal.image" (dict "global" .Values.global "image" .Values.redis.image) }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          command:
            - redis-server
            - "--maxmemory"
            - {{ .Values.redis.maxmemory | quote }}
            - "--maxmemory-policy"
            - "noeviction"
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli ping
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: redisdata
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: redisdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.redis.storage.storageClassName }}
        storageClassName: {{ .Values.redis.storage.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.storage.size | quote }}
{{- end }}
