# SPDX-FileCopyrightText: 2026 Ravi Chopra <shivamchopra1234567890@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-only
{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "observal.fullname" . }}-init-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "observal.fullname" . }}-init-role
subjects:
  - kind: ServiceAccount
    name: {{ include "observal.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
