"""OpenCode plugin specification.

OpenCode uses JS/TS plugins rather than shell command hooks.
We generate a minimal JS plugin that calls the observal hook scripts.
"""

from __future__ import annotations

OPENCODE_PLUGIN_EVENTS = (
    "session.created",
    "session.idle",
    "session.error",
    "session.compacted",
    "tool.execute.before",
    "tool.execute.after",
    "file.edited",
)
OPENCODE_STOP_EVENTS = ("session.idle", "session.error")


def build_opencode_plugin_js(hook_script: str, stop_script: str) -> str:
    """Build the JS plugin source for OpenCode.

    OpenCode plugins are JS modules that export an async function.
    This plugin spawns the observal hook shell scripts on each event.
    """
    return f"""// Observal telemetry plugin for OpenCode
// Auto-generated by `observal pull`
import {{ execSync }} from "child_process";

const HOOK_SCRIPT = {_js_str(hook_script)};
const STOP_SCRIPT = {_js_str(stop_script)};

function fireHook(script, event, input) {{
  try {{
    execSync(script, {{
      input: JSON.stringify({{ hook_event_name: event, ...input }}),
      timeout: 10000,
      stdio: ["pipe", "pipe", "pipe"],
    }});
  }} catch (e) {{
    // Non-blocking: don't break the session
  }}
}}

export const ObservalPlugin = async ({{ project, client }}) => {{
  return {{
    "session.created": () => fireHook(HOOK_SCRIPT, "session.created", {{}}),
    "session.idle": () => fireHook(STOP_SCRIPT, "session.idle", {{}}),
    "session.error": (input) => fireHook(STOP_SCRIPT, "session.error", input),
    "session.compacted": () => fireHook(HOOK_SCRIPT, "session.compacted", {{}}),
    "tool.execute.before": (input) => fireHook(HOOK_SCRIPT, "tool.execute.before", input),
    "tool.execute.after": (input, output) => fireHook(HOOK_SCRIPT, "tool.execute.after", {{ ...input, output }}),
    "file.edited": (input) => fireHook(HOOK_SCRIPT, "file.edited", input),
  }};
}};
"""


def _js_str(s: str) -> str:
    """Escape a string for JS source."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
