# SPDX-FileCopyrightText: 2026 Apoorv Garg <apoorvgarg.21@gmail.com>
# SPDX-FileCopyrightText: 2026 Hari Srinivasan <harisrini21@gmail.com>
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: Observal ClickHouse
    type: grafana-clickhouse-datasource
    uid: observal-clickhouse
    access: proxy
    isDefault: true
    jsonData:
      host: observal-clickhouse
      port: 8123
      protocol: http
      defaultDatabase: observal
      username: default
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD
    editable: true
