# SPDX-FileCopyrightText: 2026 Kaushik Kumar <kaushikrjpm10@gmail.com>
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: observal-prometheus
    access: proxy
    url: http://observal-prometheus:9090
    isDefault: false
    editable: true
